### ISSUE TITLE
Search by files around already opened ones

### ISSUE THREAD

**Issue by anki-code** [young-developer/nppNavigateTo#12]
Hi! Thank you for your great idea and plugin!

Many IDEs have a feature to search by all files in project. For example all JetBrains IDEs open the menu like NavigateTo after triple `Shift`.

It will be great if NavigateTo can be search files around already opened ones. For simplest way the files can be found in the folders of opened files without recursion diving in subfolders.

For example this feature can be activated when user type the name but filtering result is empty. In this case NavigateTo start to search files around. And the start folder will be the folder of current opened file.

Thank you!

⬇️ Please click "+1" icon instead of "+1" comment

**Comment by young-developer** [comment]
I am currently working on this idea. I want to run such search in multi thread way.

**Comment by young-developer** [comment]
New plugin v2 is available. Please retest and let me know if something else can be added/changed: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.0.0
