### ISSUE TITLE
Only the first file, of the "secondary" view, is displayed in NavigateTo plugin, v 1.12.4

### ISSUE THREAD

**Issue by guy038** [young-developer/nppNavigateTo#13]
Hello, @young-developer,

I noticed **two** issues, with **NavigateTo** **`v1.12.4`** : a tiny one and a bigger one !

- First, when you **right**-click on the **NatigateTo.dll** file ( **`158,720`** bytes ), and select the **Properties**, at bottom, then select the **Version** tab it still shows **`1.12.3`**, instead of **`1.12.4`**. Luckily, from **within** N++, if you choose the **Plugins > Navigate To > About** option, it **correctly** displays the **`1.12.4`** version

- Secondly, I noticed that, if you have **two** views, in your **current** N++ session, with some files in **`view 0`** and some others in **`view 1`**, the **Navigate To** list shows :

- All files  of the **view 0** ( the **main** view )

- Only the **very first** file of the **view 1** ( the **secondary** view )

---

Now, **anki-code** said :

>For example this feature can be activated when user type the name but filtering result is empty. In this case NavigateTo start to search files around. And the start folder will be the folder of current opened file.

Indeed, when the characters **typed** in, by the user, **cannot** be found, in names of **all** the **opened** documents, it could be interesting to search, automatically, in the **folder** of the **current** opened file, for any **other** file, whose name **matches** the **typed** characters, and outputs them in a **new** list. Then, double-clicking, on **one**, or **several** of them, would, simply, **open** them, in N++ and close the **Navigate To** window

Best Regards

guy038

**Comment by young-developer** [comment]
@guy038 I am investigating.

**Comment by young-developer** [comment]
Should be fixed in : https://github.com/young-developer/nppNavigateTo/releases/tag/v.1.12.6
