### ISSUE TITLE
Bugs, related to "secondary" view, in NavigateTo plugin, v1.12.3.0 and v1.12.4.0 !

### ISSUE THREAD

**Issue by guy038** [young-developer/nppNavigateTo#14]
Hello, @young-developer,

I'm **quite** sorry for this **very late** reply, but I noticed some problems, with **both** versions **`1.12.3.0`** and **`1.12.4.0`**

First of all, these problems could be, simply, related to my **Win XP** configuration. Here is, below, the **Debug Info** :

~~~diff
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : D:\@@\756\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows XP (32-bit)
Plugins : ComparePlugin_2.0.dll DSpellCheck.dll HTMLTag_unicode.dll LuaScript_0.71.17.dll mimeTools.dll NavigateTo_1.12.2.0.dll NppConverter.dll nppcrypt_1.0.1.3.dll NppExport.dll NppTextFX.dll PreviewHTML.dll PythonScript.dll VIsimulator.dll 
~~~

So, briefly :

**`v12.4`** : **Wrong** version number ( still **`v1.12.3.0`** instead of **`v1.12.4.0`** )

---

- **`v12.3`** : Column VIEW **NOT** visible in "**NavigateTo**" dialog

- **`v12.4`** : **Same** problem

---

- **`v12.3`** : The **first** file, of **VIEW `1`**, is **absent** of the list

=> Necessity to **close** this file ( **`Ctrl + W`** ) and **re-open** it ( **`Ctrl + Shift + T`** ) or **re-start** N++ to get it **visible**, in the list

- **`v12.4`** : **OK**, no problem

---

- **`v12.3`** : **All** the files, in **VIEW `2`**, are **invisible**, in the list

- **`v12.4`** : **Only** the **first** file, in **VIEW `2`**, is **visible** in the list

---

- **`v12.3`** : **Double**-click, **selection** or **Enter** on a file, of **VIEW `1`** => **OK**

- **`v12.4`** : **Double**-click, **selection** or **Enter** on a file, of **VIEW `1`** => **OK**

- **`v12.4`** : **Double**-click, **selection** or **Enter** on the UNIQUE file, of **VIEW `2`**, **visible** in the list

=> The **last** file, of **VIEW `2`**, although **invisible** in the list, is **WRONGLY** selected !

---

- **`v12.3`** : If **move** of files, from **VIEW `2`** to **VIEW `1`**, they are **absent**, in the list

=> Necessity to **close** this file ( **`Ctrl + W`** ) and **re-open** it ( **`Ctrl + Shift + T`** ) or **re-start** N++ to get it **visible**, in the list

- **`v12.4`** : **Same** problem

---

- **`v12.3`** : If **move** of files, from **VIEW `1`** to **VIEW `2`**, they are **absent**, in the list

=> Necessity to **close** this file ( Ctrl + W ) and **re-open** it ( Ctrl + Shift + T ) or **re-start** N++ to get it **visible**, in the list

- **`v12.4`** : If **move** of  files, from **VIEW `1`** to **VIEW 2``**, they are **ABSENT**, in the list

After **closing** this file ( **`Ctrl + W`** ) and **re-opening** it ( **`Ctrl + Shift + T`** ) or after **re-starting** N++

=>  **Only** the **first** file, of **VIEW `2`**, is **visible**, in the list

---

So, I'm **still** using the **`1.12.2.0`** version, on my **XP** laptop, which works **fine**, **without** any bug :-))

Again, @young-developer, all these **bugs** could appear because of **Win XP** !

Many **thanks** for your future **investigation** :-))

Best Regards,

guy038

**Comment by young-developer** [comment]
@guy038 Please check the latest version.
https://github.com/young-developer/nppNavigateTo/releases/tag/v.1.12.6
