### ISSUE TITLE
Newly created files not getting detected by the plugin

### ISSUE THREAD

**Issue by jurko-gospodnetic** [young-developer/nppNavigateTo#15]
Extracting this from issue #8 as it appears to still be happening with release 1.12.4.

When you create a new file in Notepad++ using `Ctrl+N`, it does not get listed by the plugin no matter what filter you enter. Saving the new file makes no difference.

The new file (even though it has not been explicitly saved to disk) does get picked up on Notepad++ restart.

Files opened from disk on the other hand are picked up and get displayed in the plugin's dialog correctly.

Notepad++ debug information:
```
Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : NavigateTo.dll PluginManager.dll DSpellCheck.dll mimeTools.dll NppConverter.dll 
```

**Comment by pidgeon777** [comment]
I also confirm this issue.

**Comment by young-developer** [comment]
@pidgeon777 @jurko-gospodnetic Please check the latest version: https://github.com/young-developer/nppNavigateTo/releases/tag/v.1.12.6

**Comment by jurko-gospodnetic** [comment]
I can confirm this works for me now with the 1.12.7 release. Thanks!
