### ISSUE TITLE
Standard input text navigation keys don't work

### ISSUE THREAD

**Issue by jurko-gospodnetic** [young-developer/nppNavigateTo#17]
When you're entering the plugin's input filter, you can not use `Home` or `End` keys to navigate in that text, including things like `Shift-End` to select all the text to the end of the current input field value.

You do seem to be able to use the arrow keys, `backspace`, `del` and `shift`.

**Comment by famod** [comment]
nppNavigateTo is a really useful plugin but this issue is driving me nuts.

**Comment by young-developer** [comment]
https://github.com/young-developer/nppNavigateTo/releases/tag/v.1.12.7

**Comment by jurko-gospodnetic** [comment]
I can confirm this works for me now with the 1.12.7 release. Thanks!
