### ISSUE TITLE
Deleting plugin filter input field content can change the input field's caret position

### ISSUE THREAD

**Issue by jurko-gospodnetic** [young-developer/nppNavigateTo#18]
When you have some filter entered in the plugin's input field that shows you no results, and you start deleting characters from that filter, at the point when some the remaining filter text matches some open file's name, the currently entered filter text will get selected and the caret will get moved to the end of the entered filter text.

This is problematic for instance if you were deleting the text at the start by pressing the `del` key.

The caret should not be moved automatically in any case during user's filter text editing except as a result of an explicit user operation for moving that caret, e.g. like pressing the arrow keys, `home` or `end` (see issue #17).

**Comment by young-developer** [comment]
https://github.com/young-developer/nppNavigateTo/releases/tag/v.1.12.7

**Comment by jurko-gospodnetic** [comment]
I can confirm this works for me now with the 1.12.7 release. Thanks!
