### ISSUE TITLE
open dialog it should display a empty search input.

### ISSUE THREAD

**Issue by souzacds** [young-developer/nppNavigateTo#19]
when you open NavigateTo dialog it should has empty input field instead of showing previous entry. Or at least give the option to this behavior.

**Comment by pidgeon777** [comment]
I prefer it to show the previous entry, but a user configurable option would accommodate every need.

**Comment by Wiethoofd** [comment]
In line with #17, being able to do a `ctrl+backspace` to empty the field would also do the trick, but is currently not supported and instead places a `` character in the search input.

Being able to default to empty (or assign a key combination to start a new empty navigation search) would be nice to have.

**Comment by mahpooya** [comment]
If content of input be selected when we open the dialog it would be better
And its very easy for developer of this magnificent plugin to do this, its not something that take years to do!

**Comment by young-developer** [comment]
@mahpooya content of input is selected in the latest version of the plugin. It can be clear by `delete` or `backspace`. 
https://github.com/young-developer/nppNavigateTo/releases/tag/v.1.12.6
I am going to move different optional functionality to settings file/form.

**Comment by Wiethoofd** [comment]
v1.12.7 fixed a bunch of issues and added support for more keys to be used in the input dialog, but `ctrl+backspace` still results in an extra `` instead of removing the previous word entered. (ctrl+shift+arrow left works, but is not as convenient)

**Comment by young-developer** [comment]
New plugin v2 is available. Please retest and let me know if something else can be added/changed: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.0.0

**Comment by young-developer** [comment]
I forgot about this settings option but I will add it in the next release version.

**Comment by young-developer** [comment]
Added in https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.1.1
