### ISSUE TITLE
Make the search window dockable

### ISSUE THREAD

**Issue by pidgeon777** [young-developer/nppNavigateTo#20]
It would be great to add an option so that the main search window could be dockable (usable as a tab among the others in the Notepad++ main window).

**Comment by careca1970** [comment]
I support the proposal.

**Comment by korpx** [comment]
+1 on this!

**Comment by young-developer** [comment]
New plugin v2 is available. Please retest and let me know if something else can be added/changed: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.0.0
