### ISSUE TITLE
NavigateTo cannot search files in the Right View

### ISSUE THREAD

**Issue by peterqtr11** [young-developer/nppNavigateTo#22]
Hi,

It seems that NavigateTo cannot search files in the Right View, it only search files in the Left View. Can you please update this function.

Thanks!

**Comment by rameshrk** [comment]
Thanks  peterqtr11 . Facing the same issue.

**Comment by rameshrk** [comment]
Thanks peterqtr11 . Facing the same issue.
Version used 1.12.4
And huge thanks to the members of this wonderful project.

**Comment by kiyn** [comment]
I confirm the issue in v1.12.4.1 and add that the files are no longer listed in NavigateTo even when from the right view they are returned to the left view.

**Comment by ronstudy1** [comment]
any plans to fix it? this issue makes the plugin useless for users who use two views

it has worked in previous versions
this is how it looked at v1.12.2:
>  ![Alt Text](https://i.imgur.com/FBSIqtC.png)

now the "view" column is gone and only left-view tabs are shown

**Comment by young-developer** [comment]
@peterqtr11 @kiyn @ronstudy1 New version should resolve the issue. Please check and let me know.
https://github.com/young-developer/nppNavigateTo/releases/tag/v.1.12.6
