### ISSUE TITLE
NavigateTo Dialog opens on primary monitor with npp on secondary

### ISSUE THREAD

**Issue by Wiethoofd** [young-developer/nppNavigateTo#23]
Steps to reproduce:
1. Have 2 or more monitors
2. Move Notepad++ off the primary monitor
3. Hit the shortcut for NavigateTo to open (using version 1.12.6)
4. NavigateTo dialog opens in the center of the primary monitor, instead of relative to the npp window that spawned it.

**Comment by young-developer** [comment]
Please try to:
1. Restart npp (It should be a new instance of npp)
2. Move Notepad++ off the primary monitor
3. Hit the shortcut for NavigateTo to open (using version 1.12.6)

P.S. The dialog keeps position after the first shortcut execution.

**Comment by young-developer** [comment]
New plugin v2 is available. Please retest and let me know if something else can be added/changed: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.0.0
