### ISSUE TITLE
Cant open dialog with `Ctrl+,`

### ISSUE THREAD

**Issue by znsoooo** [young-developer/nppNavigateTo#25]
Test on Windows 10 64 bit, npp v7.6.3 32-bit and npp v8.4.2 32-bit, NavigateTo v1.12.7.

The dialog can called by menu bar, but cant react with hot key `Ctrl+,`. Do I need to do any other settings before?

**And suggestions:**

Navigate filter cant react with `Ctrl+C` and `Ctrl+V`. Sometimes I copy a filename in a source code, and I want to search it in navigate bar, so I use `Ctrl+V` to paste text into navigate filter.

And, can the search bar support multiple keywords separated by spaces? If difficult to support regEx, space-separated keywords will be easier?

**Comment by young-developer** [comment]
@znsoooo Check you shortcuts mapping: Settings -> Shortcut Mapper.
I tested and copy and paste functionality and it works correctly. Most probably something with shortcuts are configured incorrectly. 
I will add multiple keywords on my list of requested features.

**Comment by znsoooo** [comment]
Thank you, I figure out that the reason is because I opened other input methods (even in English input mode). It's ok after closing.
So I think you may consider whether to replace the default key settings (although it can switch manually), because after all, there are still many users in countries who need to use the input method.

**And the Paste problem** (the corner is the keystroke log):
https://user-images.githubusercontent.com/34830785/179318791-b3f5127e-1fe8-40ec-a93b-60501eb6ecc2.mp4

**Comment by korpx** [comment]
Have the same problem with the shortcut not working. CRTL, + is a common shortcut for increasing the font size in Windows. It's be nice to be able to change the shortcut for the plugin thru a settings dialog or at least a config textfile.

**Comment by young-developer** [comment]
@korpx In shortcut mapper settings you can set it to any other.
![image](https://user-images.githubusercontent.com/4460168/201312676-a2198515-0f19-4469-99d5-f57f8e84233c.png)

**Comment by young-developer** [comment]
@korpx Oh ok. I found there were changes for the codebase. I will fix it in the next release.
