### ISSUE TITLE
Easily better than FileSwitcher, except for one feature

### ISSUE THREAD

**Issue by Skrell** [young-developer/nppNavigateTo#26]
Could you possible add the ability to autosize the columns of the search results?  Or at the very least save the dimensions from session to session after I close down NPP?   Bonus feature would be ability to close multiple results tabs at once, but the fact I can close 1 at a time is still GREAT!!

**Comment by young-developer** [comment]
Hi @Skrell 
I am working on v2 for this plugin. I will include it in the next version.

**Comment by Skrell** [comment]
Awesome thank you!

**Comment by young-developer** [comment]
@Skrell 
New plugin v2 is available. Please retest and let me know if something else can be added/changed: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.0.0
