### ISSUE TITLE
"new 1" phantom tab/file? 

### ISSUE THREAD

**Issue by Skrell** [young-developer/nppNavigateTo#28]
"new 1" doesn't exist in ANY tab? 
![image](https://user-images.githubusercontent.com/590266/204381064-d1d4d262-f48b-4a29-951d-58b8ac528ecf.png)

**Comment by molsonkiko** [comment]
I had the same issue!

![new 1 phantom tab](https://user-images.githubusercontent.com/46202915/204430257-7ad99c7e-d389-4faf-b3b1-eefddd92d8b6.PNG)

**Comment by young-developer** [comment]
Honestly have no idea why it returns this new file. It disappears if there are files in primary and second view at the same time. Still investigating...

**Comment by young-developer** [comment]
Fixed in 4.2.1.
