### ISSUE TITLE
Please show result count, like in previous version!

### ISSUE THREAD

**Issue by molsonkiko** [young-developer/nppNavigateTo#29]
I really like the new version, especially the ability to quickly select files in the same project as the current file.

That said, one of the things I really liked about the old NavigateTo was the ability to quickly tell at a glance how many tabs I had open. Probably what would make the most sense would be to show it in a little text box at the bottom of the grid.

**Comment by young-developer** [comment]
https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.2.1
