### ISSUE TITLE
List of matching files isn't updating correctly

### ISSUE THREAD

**Issue by tjmv** [young-developer/nppNavigateTo#3]
At some times the list of matching files is completely empty, even though in the title it says "Found x matching results" (where x > 0). As far as I know, it only happens when starting NP++. I haven't completely narrowed down the cause, but I could only "fix" it by closing all opened documents until I got to a new file.

**Comment by young-developer** [comment]
@tjmv Could you send me your " ? > Debug Info" from Notepad++?

**Comment by tjmv** [comment]
`
Notepad++ v7.4.1   (64-bit)
Build time : May 18 2017 - 02:02:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NavigateTo.dll NppConverter.dll 
`

Unfortunately I don't exactly know how to reproduce it. The only similarity I know of between the sessions is that I had a large number of files open (~50). In fact it first happened when I manually compiled the plugin, so I just assumed I did something wrong. But it happened a few times with the "official" download.

I didn't know where to start looking so I decided to post the issue here.

**Comment by young-developer** [comment]
@tjmv , Hm...I have already tested it on x32 and It looks like it works well... ok I will try to repeat it on x64 version as well mb I will find something.

**Comment by tjmv** [comment]
I tried it again and I can reproduce it, but it took _a lot_ of opened files this time, even though I'm sure I don't have that many open during a normal session. Not sure about all of the files that have been opened in the past during a single session, though. When trying to reproduce it, I had 225 files open, closed Notepad++ and the file list was empty. Then I closed a file, restarted the application, opened the file again and it wasn't empty...

**Comment by young-developer** [comment]
Hi, @tjmv  try this version https://github.com/young-developer/nppNavigateTo/releases/tag/1.12.2-beta

**Comment by tjmv** [comment]
Nope, the issue is still present and I still have no idea how to properly reproduce it. This time I had 52 files open (which is quite common when searching for a certain variable and not knowing exactly how it is used) and closing NPP and starting it again resulted in the list being empty. I then tried to open a bunch more and I noticed that the "Found xx matching results" did not update even on an empty filter. However, it was not consistent. One time opening a certain file did make it bug out while other times it did not and I had to open a few more while restarting NPP every time. All I can say is that it is not fixed and the only workaround is to restart NPP, but that doesn't always work.

**Comment by young-developer** [comment]
@tjmv Please try x32 version. It works well for me. https://github.com/young-developer/nppNavigateTo/releases/tag/1.12.3

**Comment by tjmv** [comment]
Unfortunately that version is completely unusable. It causes Notepad++ to crash every single time I open a new file after using the file switcher, even after removing the program data from my user profile. This is from a zip I just downloaded with only this plugin added and a blank user profile.

I couldn't find a memory dump, but visual studio showed the following exception:
`Unhandled exception at 0x6AFCEAA7 (comctl32.dll) in notepad++.exe: 0xC000041D: An unhandled exception was encountered during a user callback.`

Debug info:
`Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Users\XXX\Downloads\npp.7.5.4.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NavigateTo.dll NppConverter.dll NppExport.dll 
`

**Comment by young-developer** [comment]
@tjmv I am trying to fix it. For sure x64 version does not work correctly. I will notify you as soon as I fix it. Do you have the same crash on x32 version?

**Comment by young-developer** [comment]
@tjmv Try new version 1.12.4 of x64 and x32bit. I have more than 100 tabs open now.

**Comment by tjmv** [comment]
I switched to another application for my main work a while back, but I've been using Notepad++ with this plugin since you posted the update here. I haven't experienced the problem whereas it used to happen very frequently. So it looks like it's fixed now. 👍
