### ISSUE TITLE
fuzzy search? 

### ISSUE THREAD

**Issue by Skrell** [young-developer/nppNavigateTo#31]
So maybe this is just me not understanding how to use fuzzy search but this is NOT what I would have expected: 
![image](https://user-images.githubusercontent.com/590266/204853414-8ff80625-62c0-4d3f-a608-439fc897f087.png)

I would have thought it would look for the && of each sequence typed not the ||

**Comment by young-developer** [comment]
@Skrell I am open to any ideas. Please send me algorithms or approaches that you think could be useful.

**Comment by Skrell** [comment]
My apologies for being difficult but I'd recommend an algorithm whereby each successive sequence of letters/numbers separated by a space searches the existing search results.  

So the first typed characters create a list of results then if the users types a " " and enters another sequence that searches the existing results list and so on in a recursive fashion.   Does this help at all?

**Comment by young-developer** [comment]
I am not sure if we are talking about the same type of search. I understand fuzzy search as search with errors like: 
- r`ea`dme -> r`e`dme
- n`a`vigate -> nvigate
and it still able to find results. Example:
![With_fuzzy](https://user-images.githubusercontent.com/4460168/205038782-2c033b6a-fdeb-4b65-8325-3b9b2c5b29e3.png)
![With_fuzzy_ex2](https://user-images.githubusercontent.com/4460168/205038790-f5095c2c-e9d2-47f0-9883-f7b3545cce91.png)
![Without_fuzzy](https://user-images.githubusercontent.com/4460168/205038797-a8e65441-2b38-4a48-8ddf-4325915dfa8a.png)

**Comment by young-developer** [comment]
@Skrell Try this version. Check release description for details: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.4.0

**Comment by Skrell** [comment]
NAILED IT!!  This plugin is officially a "must have" for ALL Notepad++ users!

**Comment by Skrell** [comment]
Damn... so your fuzzy search is searching for individual characters unfortunately..   
![image](https://user-images.githubusercontent.com/590266/205106666-3f137b12-70c8-4f00-9d95-2263d797d9ee.png)

**Comment by young-developer** [comment]
Its just highlight individual chars. It searches according to this algo: https://en.wikipedia.org/wiki/Longest_common_subsequence_problem

**Comment by Skrell** [comment]
So if I'm understanding, the search results are correct but the highlighting is wrong?
