### ISSUE TITLE
The search line edit ignores the first typed key when "Clear search input" is enabled in the settings

### ISSUE THREAD

**Issue by roromo** [young-developer/nppNavigateTo#33]
Steps to reproduce the bug:
- enable "Clear search input" in the plugin settings
- open the plugin dialog window (Ctrl+,)
- start typing something like: 4090
- the first typed character is ignored, the search line edit shows "090" and only the "090" entries are listed and highlighted in the search results

**Comment by young-developer** [comment]
It depends on multiple settings. If you have enabled fuzzy search than it is possible and known. Please could you try to test with disabled fuzzy search : [Documentation](https://github.com/young-developer/nppNavigateTo/tree/master/documentation)

**Comment by roromo** [comment]
Fuzzy search is disabled. Here is a screenshot of the settings:
![Screenshot 2023-04-26 131424](https://user-images.githubusercontent.com/47000230/234545295-02e324fe-fea2-42db-a347-4f7c30fb9afd.png)

In the meantime, I discovered the issue reported here happens only when the first typed character is a number (such as 4). It works fine when the first character typed is a letter.

**Comment by young-developer** [comment]
fixed in https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.4.2
