### ISSUE TITLE
No data when Notepad++ is first opened

### ISSUE THREAD

**Issue by seowner** [young-developer/nppNavigateTo#36]
Hi,

I think this plugin is really, really good. But there's a huge problem that I don't understand. When you first open Notepad++ and press the hotkey to open the menu, there's no data in it. No files, nothing at all.

To solve this, you can click on a tab then the menu is populated. But being this is going to replace the top tabs, it's really frustrating to have to click one of them to get data in the NavigateTo plugin!

Note 1: This only happens in v2.0+. I went back and tested an old version (v1.12.7) and the menu is populated fine when Notepad++ is opened.

Note 2: The menu has to be open when you click a tab for it to populate.

Also, it would be really nice to have an "only search filenames" option, because I really don't see a difference when using "Prefer filename over path." But the main issue is the menu not populating.

You can see what I mean here:
[https://i.imgur.com/tfY7Tc4.jpg](https://i.imgur.com/tfY7Tc4.jpg)

**Comment by young-developer** [comment]
So it is known functionality. Someone asked about it as far as I can remember. Maybe I should move it to optional functionality.

**Comment by alankilborn** [comment]
I have to agree with @seowner strongly on this.  Having the plugin show you, well, nothing, when it first opens is a turn-off for new users.

**Comment by molsonkiko** [comment]
Hopefully this is resolved in [version 2.6.4](https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.6.4).
