### ISSUE TITLE
Layout broken on 4k screen

### ISSUE THREAD

**Issue by tiomanisland** [young-developer/nppNavigateTo#37]
I have Dell XPS 17, 4k screen. When I try to use this plugin, line spacing is too small, lines overlap and it is impossible to use it. Is it possible to fix this?

**Comment by tiomanisland** [comment]
HELLO?

**Comment by young-developer** [comment]
Please could you send screenshots?

**Comment by Ythan** [comment]
I'm not the original submitter of this bug, but I am also affected. It looks like it doesn't properly account for the display scaling setting in Windows. In [this screenshot](https://www.mind-media.com/images/bug.png) I am using 250% scaling.

Thanks for the useful plugin and please let me know if there's anything I can do to help debug.

**Comment by young-developer** [comment]
@Ythan Is it only for docked version?
P.S. I tested different scalings and it scales well.

**Comment by tiomanisland** [comment]
Exactly same here. I use normal version. Notepad++ and this plugin downloaded from plugin manager. Windows 11, 4k screen.

**Comment by young-developer** [comment]
@Ythan @tiomanisland Please could you send me plugin`s Settings page?

**Comment by Ythan** [comment]
Awesome, 2.4.3.91 is definitely [improved](https://www.mind-media.com/images/bug2.png). The input field is now sized properly, although the column headers are still too small. Seems like you're on the right track though. Thank you for your attention to this bug!

Not sure if it's still relevant, but to answer your questions: it doesn't matter if the plugin is docked or windowed, and the settings are as follows:

[NavigateTo]
columnNameWidth=24
columnPathWidth=66
columnSourceWidth=10
keepDlgOpen=1
gridMinWidth=300
sortAfterFilterBy=-1
sortOrderAfterFilterBy=0
gridTextColor=-16777216
gridSelectedRowBackground=-16746281
gridSelectedRowForeground=-16777216
gridBackgroundColor=-5526613
highlightColorBackground=-23296
rowBackgroundColor=-1

**Comment by Ythan** [comment]
Thank you for the update. I have doubled the gridMinWidth setting and installed 2.4.3.92 of the plugin, however the column headers [still apppear to be truncated](https://www.mind-media.com/images/bug3.png).

**Comment by young-developer** [comment]
@Ythan I changed to AutoSize for headers. Not sure if it can fix because it is handled by Windows. Please double check latest version ([here](https://ci.appveyor.com/project/young-developer/nppnavigateto/history)).

**Comment by Ythan** [comment]
It works! Version 2.4.3.93 displays [exactly as expected](https://www.mind-media.com/images/fixed.png) and looks right at home now with DPI scaling enabled. Thank you again for your attention to this bug, especially considering it didn't even affect your setup. Hopefully some other users will also benefit.

**Comment by young-developer** [comment]
New release: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.4.3
