### ISSUE TITLE
Auto-closing the NavigateTo popup once Enter is pressed

### ISSUE THREAD

**Issue by albino1** [young-developer/nppNavigateTo#38]
Hey there,

First off, I just wanted to say that I absolutely love this plugin, it's saved my life since I always have a lot of tabs open.  The fact that you can search by path is just amazing.

I originally docked it, but then I decided I liked it better as a popup in the middle of the screen instead, but realized that after I hit enter to switch to the file I still needed to then hit `CTRL+,` to close the popup window.

I got around this by making a little AutoHotKey script that just sends `Enter` followed by `CTRL+,` so that the window closes automatically when you open the file:

```
#IfWinActive, ahk_exe notepad++.exe
#IfWinActive, NavigateTo
Enter::
SendInput, {Enter}
SendInput, ^,
#IfWinActive
return
```

(Apologies for my super basic AutoHotKey code, it could probably be done better)

This totally works, and I'm happy with it, but I thought I would mention it here for two reasons.  The first is in case anybody else is looking for a similar solution, maybe they might find this script useful.  The second is that I actually think this would be a good option in the main plugin settings instead of working around it with something like AutoHotKey.

So I guess consider this a feature request.  Thanks!

**Comment by young-developer** [comment]
@albino1 Please check plugin settings form, there is such setting.

**Comment by albino1** [comment]
I tried looking before, but I now realize what I was looking for is `Keep dialog visible`, but it seems like the behavior is reversed from what you would expect?  If I check `Keep dialog visible` then the box disappears, but if I uncheck it then the box stays visible.  Maybe I'm misunderstanding it though.

Either way, you're right in that this does work, and there's no script required, thanks for pointing me in the right direction!
