### ISSUE TITLE
Change target .NET Framework to 4.8

### ISSUE THREAD

**Issue by molsonkiko** [young-developer/nppNavigateTo#39]
All that needs to be done is change line 13 of the `csproj` to `<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>`

Reasons to go to .NET Framework 4.8:
* Visual Studio 2022 (you need to install a targeting pack for 4.0, which is a hassle)
* you can use the [MSBuild GitHub action](https://github.com/microsoft/setup-msbuild), which is really nice because it means that your compiled x86 and x64 binaries are stored as artifacts that anyone can download without having to build your project from source

I do recognize that .NET Framework 4.8 is not installed by default on Windows versions before [Windows 10 May 2019 update](https://blogs.windows.com/windowsexperience/2019/05/21/how-to-get-the-windows-10-may-2019-update/), and that was indeed my rationale for dragging my feet in moving to 4.8 for JsonTools. But since moving to 4.8, I've been really happy with the change. My general impression is that very few people are likely to not have .NET 4.8 installed on their computers anyway.

I'm mostly submitting this issue for selfish reasons because I want to submit a PR and I can't work on NavigateTo in Visual Studio without changing the TargetFramework to 4.8.

**Comment by young-developer** [comment]
We can keep this ticket open in case there will be some issues related to upgrade.
