### ISSUE TITLE
Keep menu open

### ISSUE THREAD

**Issue by cmeriaux** [young-developer/nppNavigateTo#4]
Is it possible to add an option so that the menu stays always open.

**Comment by young-developer** [comment]
@cmeriaux , It will be added as new feature to Options form later. User will be able to check/uncheck "Hide after focus lost" option. Thank you for feedback.

**Comment by young-developer** [comment]
@cmeriaux @pidgeon777 
Try to preview files using Shift + Arrow Up/Down. 
I will add additional settings to keep the window open.

**Comment by young-developer** [comment]
New plugin v2 is available. Please retest and let me know if something else can be added/changed: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.0.0
