### ISSUE TITLE
cache files in current file's directory

### ISSUE THREAD

**Issue by molsonkiko** [young-developer/nppNavigateTo#40]
Currently the list of files in the current directory is regenerated every time the file list is regenerated. This is unnecessary. You should instead keep the files in the current directory as an instance variable of the form and keep track of whether it has been regenerated since the user last activated the current buffer. This way, the file list is regenerated the first time the user makes a query when a given buffer is open, and then is simply reused for all subsequent queries in that buffer.

I tried this myself and it affords a significant performance improvement. I can submit a PR, but since I'm using .NET Framework in my fork, you'd have to go up to .NET 4.8 to accept it.

**Comment by young-developer** [comment]
Good point. I think it should be moved to settings as additional option because it may confuse users if they add new file to a folder and cache is not invalidated.

**Comment by molsonkiko** [comment]
Good point! But easy fix for that: have a timestamp that's set every time a current-file-directory refresh completes, and only do a refresh if the last refresh was at least 10 seconds (customizable parameter) ago.

**Comment by molsonkiko** [comment]
Comparing the last refresh time to the [LastWriteTime](https://learn.microsoft.com/en-us/dotnet/api/system.io.filesysteminfo.lastwritetime?view=netframework-4.0#system-io-filesysteminfo-lastwritetime) property of the directory's DirectoryInfo object might also work
