### ISSUE TITLE
Performance issue: Notepad++ takes very long to close itself when this extension is installed

### ISSUE THREAD

**Issue by roromo** [young-developer/nppNavigateTo#44]
I have two PCs, an Intel Haswell 4790K one, an an AMD 5900x one. On both of them I have around **180** text files permanently open in Notepad++, and I use NavigateTo to easily switch between them.

One thing I noticed after installing this extension, is that the time Notepad++ takes when I close it has greatly increased. On the Intel Haswell system, it's ~10 seconds, while on the AMD one is ~4 seconds. If I remove the "NavigateTo" folder from the Notepad++ plugins extension folder, then Notepad++ goes back to closing very quickly.

There must be something the extension does when Notepad++ is closed that increases the time it takes to close itself. Maybe it reacts to every file being removed form the list of open files? Please have a look and see if this can be improved.

**Comment by young-developer** [comment]
@roromo did you test the latest version? - https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.5.0

**Comment by roromo** [comment]
No, I was not using the beta version. Tested it know and it works fine with it!

I'll close the bug.
