### ISSUE TITLE
Crash with 1.12.2 (back to 1.8.2)

### ISSUE THREAD

**Issue by atorr0** [young-developer/nppNavigateTo#5]
Hi,

This version always crashes my NPP (only tested the 32 bit version). I had to go back to1.8.2 and it works nicely.

Thank you for such good plugin!!

PS: Windows 64bits 10.0.15063

**Comment by tithom** [comment]
Hi,
I have the exact same problem (nodepad 7.5.1), same plugin version, same OS.
Don't know if it is related, but the installation with the plugin manager doesn't work as well.

**Comment by atorr0** [comment]
I had to uninstall and re-install it manually.

**Comment by young-developer** [comment]
Hi, @atorr0 , @tithom   Please try to install manually this beta release https://github.com/young-developer/nppNavigateTo/releases/tag/1.12.2-beta

**Comment by dhowland** [comment]
I have experienced a crash since installing it, but i haven't proven it was NavigateTo.

**Comment by dhowland** [comment]
Update: yeah it's NavigateTo.  If I open multiple python files with the dialog open it crashes.

**Comment by young-developer** [comment]
@dhowland , Could you send me full file path for these files?

**Comment by young-developer** [comment]
@dhowland  and what version of npp do you use?

**Comment by young-developer** [comment]
@dhowland , New release - https://github.com/young-developer/nppNavigateTo/releases/tag/1.12.3

**Comment by tithom** [comment]
Thanks, it seem's fine for me (the beta was already fine for me too, I don't have python file).

**Comment by atorr0** [comment]
Hi all,

Everything seems fine now. I have upgraded to latest NPP (7.5.4 x32),
removed old version, and then installed it with the update manager.

Thank you!

2018-01-12 18:28 GMT+01:00 Oleksii Maryshchenko <notifications@github.com>:

**Comment by young-developer** [comment]
According to change log from last npp version 4.5.4(x32):
- 1.  Fix a crash bug due to disordered notifications sent to plugins.
