### ISSUE TITLE
Strange behaviour when pressing Ctrl-A in the filter input box

### ISSUE THREAD

**Issue by jurko-gospodnetic** [young-developer/nppNavigateTo#7]
When the plugin's main dialog is open, pressing `Ctrl-A` to select the currently entered text in the filter input box behaves strangely for me.

Don't know if it occurs in other cases, but I can reproduce it somewhat reliably when I have have many tabs open, enter only a single letter as a filter and the list control below it ends up containing more files then can fit on the screen (so the scroll-bar appears).

Effects are:
1. pressing `Ctrl-A` often seems to cause the entire list control content to flicker
2. pressing `Ctrl-A` causes the current list control selection to change back to the first displayed row
3. pressing `Ctrl-A` occasionally does not select the filter text, but instead clears the current selection and just moves the caret to the end of the currently entered input text
4. several times when clearing the current filter and then closing the dialog, reopening it and pressing Ctrl-A, I've see the previous filter text be restored

The effects do not occur if the whole currently entered filter text is already selected, so the code might be short-circuiting its regular behavior and just doing nothing on `Ctrl-A` in that case.

The effects are also sometimes affected by:
- whether you last typed in the filter input text box or moved around on the list control
- whether you changed focus to a different application and back or whether you just opened the dialog

When the filter text selection problem does occur, then it occurs most of the time if not always, but then after a while it starts working ok again and can't be reproduced for a while.

### Reproducible use-case

One strange use-case that seems to reproduce some of these issues in all the cases I've tried it:
1. open the plugin's main dialog
2. enter some filter text so the input box is populated with at least some data
3. select the entered filter text
4. `Alt-Tab` to a different application
5. `Alt-Tab` back to Notepad++
6. you should be back the the plugin's main dialog, but the current selection has been lost
7. pressing `Ctrl-A` will now not select the entered filter text
8. `Alt-Tab` to a different application
9. `Alt-Tab` back to Notepad++
10. you will now be back in Notepad++, but the plugin's main dialog will have been closed (if you look more closely, you notice the dialog diapears on `Alt-Tab` out and not the one coming back to Notepad++)

This also illustrates a separate issue with `Alt-Tab` out of Notepad++ affecting the plugin's main dialog, which I believe it should not do in any way.

### Notepad++ debug info

```
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NavigateTo.dll NppConverter.dll PluginManager.dll 
```

### Random thoughts on what might be behind these problems

There might be a race condition between the list control refreshing its content (which it should not have to do in the first place, just for a selection change) and setting the current selection in the filter input box. In that case, possibly some internal focus change that occurs due to the list control refresh makes Notepad++ forget/reset the current filter input box selection.

You might have two different system vying for control over those keyboard shortcuts, e.g. some system inherent to the input box control used and some higher level one built in the plugin application itself.

You might have tried to do some special handling for `Alt-Tab` out of Notepad++, possibly to have it disappear then, which I believe should not be done and Notepad++ losing focus should leave the plugin's main dialog as is for use when Notepad++ application receives back the focus.

**Comment by young-developer** [comment]
@jurko-gospodnetic Fixed in v.1.12.4.
