### ISSUE TITLE
Selects incorrect files at times + followup issues

### ISSUE THREAD

**Issue by jurko-gospodnetic** [young-developer/nppNavigateTo#8]
I have a lot of files open in my Notepad++ at the moment - cca 200., with multi-line tabs enabled. Some of those tabs contain files that have been saved on disk and some that have not (named `New 1`, `New 42` and alike)>

Plugin correctly lists all of those files, but selecting them from the plugin's main dialog does not always select the correct tab. Some of the files it selects correctly, but on many of the files it actually selects the first tab following the desired tab.

At first I thought this only happened when selecting files that have not been saved on disk yet, but it seems to be unrelated. I have found such both saved & unsaved files that it selects correctly and those that it does not.

### Related problems encountered when trying to provide more info for this issue

Repositioning the tabs in Notepad++ might have something to do with this, as when I repositioned a tab just now, it messed up the plugin even more. When searching for the file in the moved tab, it now selects the tab that's in the position where this file's tab used to be positioned.

Also, opening a new tab and not saving it yet (named `New 27` in my case) does not seems to get that file detected by the plugin. No matter what filter I enter, the file is not listed. Saving the file afterwards does not get it listed either.

Restarted Notepad++ afterwards, which reopened all the tabs correctly, and the plugin seems to have been left in a completely unusable state. Opening the main plugin dialog just shows the old `Found 179 matching results` title and does not change it or list any files no matter what filter text I enter into it.

I also noticed that now, unlike in issue $7, the plugin's main dialog closes every time on <Alt-Tab> out of Notepad++.

I'll leave my Notepad++ in this state for as long as I can. Hopefully you can contact me before I have to change it, in case you want to look into the issue more closely. If needed you can contact me via Skype (profile: `jurkog`) or e-mail (mail server: `pke.hr`, name: `jurko.gospodnetic`).

### Notepad++ debug info

```
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NavigateTo.dll NppConverter.dll PluginManager.dll 
```

**Comment by young-developer** [comment]
@jurko-gospodnetic , Please try new version of plugin. Some of issues were resolved.
