### ISSUE TITLE
First tab not included in search box

### ISSUE THREAD

**Issue by atorr0** [young-developer/nppNavigateTo#9]
Hi,

It seems that the first tab is not included in the search box.

Info:
* Notepad++ 7.5.4 (32-bit)
* Navigate To 1.12.3

Thanks,

**Comment by atorr0** [comment]
Hi,

I can confirm this issue, as you move the tab then it becomes available in the search box.

Thx,

**Comment by young-developer** [comment]
@atorr0 , Please try new version of plugin.
